#!/bin/bash

rm -rf classes
mkdir -p classes

export JAVA_HOME="/opt/openjdk-bin-11.0.13_p8"

for JAR in $(cs fetch \
    org.typelevel:jawn-parser_3:1.2.0 \
    org.typelevel:jawn-ast_3:1.2.0 \
    javax.servlet:javax.servlet-api:3.0.1 \
    net.java.dev.jna:jna:5.10.0 | grep -v scala)
do
  unzip -q -n -d classes $JAR
done

#for JAR in /home/propensive/pub/dotty/dist/target/pack/lib/*.jar
for JAR in ~/niveau/scala/dist/target/pack/lib/*.jar
do
  unzip -q -n -d classes $JAR
done

CLASSPATH="classes:$(cs fetch \
    org.typelevel:jawn-parser_3:1.2.0 \
    org.typelevel:jawn-ast_3:1.2.0 \
    javax.servlet:javax.servlet-api:3.0.1 \
    net.java.dev.jna:jna:5.10.0 | grep -v scala | tr '\n' ':')"

#/home/propensive/pub/dotty/dist/target/pack/bin/scalac \
/home/propensive/niveau/scala/bin/scalac \
    -d classes \
    -classpath "${CLASSPATH::-1}" \
    -language:experimental.fewerBraces \
    -language:experimental.erasedDefinitions \
    -language:experimental.saferExceptions \
    -Wunused:all \
    -deprecation \
    -feature \
    -new-syntax \
    -Yrequire-targetName \
    -Ysafe-init \
    -Ycheck-all-patmat \
    -Yexplicit-nulls \
    $@ \
    src/core/*.scala \
    ../niveau/mod/acyclicity/src/core/*.scala \
    ../niveau/mod/adversaria/src/core/*.scala \
    ../niveau/mod/caesura/src/core/*.scala \
    ../niveau/mod/cataract/src/core/*.scala \
    ../niveau/mod/clairvoyant/src/css/*.scala \
    ../niveau/mod/clairvoyant/src/time/*.scala \
    ../niveau/mod/clairvoyant/src/html/*.scala \
    ../niveau/mod/clairvoyant/src/http/*.scala \
    ../niveau/mod/contextual/src/core/*.scala \
    ../niveau/mod/cosmopolite/src/core/*.scala \
    ../niveau/mod/escapade/src/core/*.scala \
    ../niveau/mod/escritoire/src/core/*.scala \
    ../niveau/mod/eucalyptus/src/core/*.scala \
    ../niveau/mod/euphemism/src/core/*.scala \
    ../niveau/mod/exoskeleton/src/core/*.scala \
    ../niveau/mod/gastronomy/src/core/*.scala \
    ../niveau/mod/gesticulate/src/core/*.scala \
    ../niveau/mod/gossamer/src/core/*.scala \
    ../niveau/mod/guillotine/src/core/*.scala \
    ../niveau/mod/harlequin/src/core/*.scala \
    ../niveau/mod/honeycomb/src/core/*.scala \
    ../niveau/mod/iridescence/src/core/*.scala \
    ../niveau/mod/jovian/src/core/*.scala \
    ../niveau/mod/kaleidoscope/src/core/*.scala \
    ../niveau/mod/probably/src/core/*.scala \
    ../niveau/mod/probably/src/cli/*.scala \
    ../niveau/mod/probably/src/tolerance/*.scala \
    ../niveau/mod/punctuation/src/core/*.scala \
    ../niveau/mod/punctuation/src/ansi/*.scala \
    ../niveau/mod/punctuation/src/html/*.scala \
    ../niveau/mod/profanity/src/java/**/*.java \
    ../niveau/mod/profanity/src/core/*.scala \
    ../niveau/mod/rudiments/src/core/*.scala \
    ../niveau/mod/scintillate/src/core/*.scala \
    ../niveau/mod/scintillate/src/server/*.scala \
    ../niveau/mod/scintillate/src/servlet/*.scala \
    ../niveau/mod/slalom/src/core/*.scala \
    ../niveau/mod/wisteria/src/core/*.scala \
    ../niveau/mod/xylophone/src/core/*.scala

cp ~/niveau/mod/exoskeleton/res/exoskeleton/invoke classes/exoskeleton/invoke
cd classes && jar cfe ../vex.jar vex.Vex * && cd ..
cat ../niveau/mod/exoskeleton/res/exoskeleton/invoke vex.jar > vex-${VERSION}
chmod +x "vex-${VERSION}"
