#!/bin/sh
# --------------------------
# Irk Launcher version ${VERSION}
# --------------------------
#
# Irk is a simplistic build tool for Scala. This launcher script will download and run Irk, replacing this
# script in the process.
#
# For more information, see https://github.com/propensive/irk/
#
# Irk, version ${VERSION}. Copyright 2022 Jon Pretty, Propensive OÜ.

set -euo pipefail
if [ ! "$(command -v java)" ]
then
  echo "It does not look like Java is installed. The 'java' command must be available on the path."
elif [ "$(java -version 2>&1 | head -n1 | awk -F '"' '{print $2}' | awk -F '.' '{print $1}')" -lt "11" ]
then
  echo "It looks like the install version of Java is not recent enough. Java 11 is required to run Irk."
elif [ ! "$(command -v curl)" ]
then
  echo "The 'curl' command must be available to download Irk. Please install Curl and try again."
else
  echo "Downloading Irk ${VERSION}..."
  curl -Lso --show-error "$0.tmp" "https://github.com/propensive/irk/releases/download/v${VERSION}/irk-${VERSION}"
  echo "Downloaded $(du -sh "$0.tmp" | cut -d'	' -f1)"
  echo 'Launching Irk for the first time...'
  chmod +x "$0.tmp"
  mv "$0.tmp" "$0"
  exec "$0" "$@"
fi
echo "Please install Java version 11 or later. See https://adoptium.net/ for free OpenJDK distributions."
exit 1
