#!/bin/bash

scli package \
    -M vex.run \
    -o vex --force \
    --standalone \
    -S 3.1.2-RC1-bin-SNAPSHOT \
    -d org.typelevel:jawn-parser_3:1.2.0 \
    -d org.typelevel:jawn-ast_3:1.2.0 \
    -d com.vladsch.flexmark:flexmark:0.62.2 \
    -d com.vladsch.flexmark:flexmark-ext-tables:0.62.2 \
    -d com.vladsch.flexmark:flexmark-ext-typographic:0.62.2 \
    -d javax.servlet:javax.servlet-api:3.0.1 \
    -d net.java.dev.jna:jna:5.10.0 \
    --progress \
    --home . \
    --jar lib/mediatypes.jar \
    --jar lib/niveau.jar \
    --jar lib/profanity-java.jar \
    -language:experimental.erasedDefinitions \
    -language:experimental.fewerBraces \
    -language:experimental.saferExceptions \
    -Wunused:all \
    -O -deprecation \
    -O -feature \
    -O -new-syntax \
    -Yrequire-targetName \
    -Ysafe-init \
    -Ycheck-all-patmat \
    -Yexplicit-nulls \
    $@ \
    src/core/*.scala \
    ../niveau/mod/acyclicity/src/*/*.scala \
    ../niveau/mod/adversaria/src/*/*.scala \
    ../niveau/mod/caesura/src/*/*.scala \
    ../niveau/mod/cataract/src/*/*.scala \
    ../niveau/mod/clairvoyant/src/*/*.scala \
    ../niveau/mod/contextual/src/*/*.scala \
    ../niveau/mod/cosmopolite/src/core/*.scala \
    ../niveau/mod/escapade/src/*/*.scala \
    ../niveau/mod/escritoire/src/*/*.scala \
    ../niveau/mod/eucalyptus/src/*/*.scala \
    ../niveau/mod/euphemism/src/*/*.scala \
    ../niveau/mod/exoskeleton/src/*/*.scala \
    ../niveau/mod/gastronomy/src/*/*.scala \
    ../niveau/mod/gesticulate/src/*/*.scala \
    ../niveau/mod/gossamer/src/*/*.scala \
    ../niveau/mod/guillotine/src/*/*.scala \
    ../niveau/mod/harlequin/src/*/*.scala \
    ../niveau/mod/honeycomb/src/*/*.scala \
    ../niveau/mod/iridescence/src/*/*.scala \
    ../niveau/mod/jovian/src/*/*.scala \
    ../niveau/mod/kaleidoscope/src/*/*.scala \
    ../niveau/mod/probably/src/core/*.scala \
    ../niveau/mod/probably/src/cli/*.scala \
    ../niveau/mod/probably/src/tolerance/*.scala \
    ../niveau/mod/probably/src/test/*.scala \
    ../niveau/mod/punctuation/src/*/*.scala \
    ../niveau/mod/profanity/src/*/* \
    ../niveau/mod/rudiments/src/*/*.scala \
    ../niveau/mod/scintillate/src/*/*.scala \
    ../niveau/mod/slalom/src/*/*.scala \
    ../niveau/mod/tarantula/src/*/*.scala \
    ../niveau/mod/wisteria/src/*/* \
    ../niveau/mod/xylophone/src/*/*.scala \
    ../niveau/src/test/*.scala
