name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout Niveau
      run: git clone --jobs=8 https://github.com/propensive/niveau niveau --recurse-submodules
    - name: Docker Build
      run: docker build --tag=vex .
    - name: Docker Run
      run: |
        docker run --name vex vex /bin/true
        docker cp vex:/vex/vex vex
        docker rm vex
