name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  full:
    name: Full build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Docker Build
      run: docker build --tag=irk .
    - name: Docker Run
      run: |
        docker run --name irk irk /bin/true
        docker cp irk:/irk/irk irk
        docker rm irk
  quick:
    name: Quick build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build
      run: ./irk

